name: myoro_fitness
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  sqlite3_flutter_libs: ^0.5.18
  path: ^1.8.3
  path_provider: ^2.1.1
  window_manager: ^0.3.7
  http: ^1.1.2
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  open_file: ^3.3.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/img/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-B.ttf
