name: myoro_fitness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-115.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.3
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
